version: '3'

services:
  postgres:
    container_name: nestjs_db
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgres/data
    env_file:
      - .env.prod
    environment:
      POSTGRES_DB: nestjs_db
      POSTGRES_USER: minjman
      POSTGRES_PASSWORD: minjman

  backend:
    container_name: nestjs_rest_api
    build:
      context: .
      dockerfile: ./Dockerfile
    image: minjman/nestjs-rest-api
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - postgres

volumes:
  db_data:
